meta_name: "My Day Out"
meta_title: "Plan my day out, anywhere in the world"
meta_description: "The app provides an itinerary of fun activities in line with your preferences"
meta_image: "https://res.cloudinary.com/danwlbu2c/image/upload/v1678834960/Icon_a9bbpe.webp"
twitter_account: "@googlemaps" # required for Twitter Cards
